[monitor]
silent = true     # 当true：日常信息日志全部静默；错误信息（例如发送失败、Cookie 失效、解析异常等）仍会输出。 当false：保持原先的详细日志。
enable = true
interval_minutes = 2      # 轮询间隔（分钟）；风控多时可调大到 3~5
jitter_seconds = 15       # 抖动（避免整点风控）

[debug]
dump_json  = false
dump_uid   = ["XXXXXXXXXX"]
output_dir = "./MaiBotOneKey/modules/MaiBot/plugins/bilibili_push_plugin/debug"

[api]
base_url = "https://api.bilibili.com"
timeout = 10
prefer_old = true 

[bilibili]
# 多组合（路由）配置：每个 routes 是一个“组合”，指定要监控的 UIDs 以及推送到的群号
# 示例：组合一，把“甲”(举例 UID 36081646) 推送到两个群；组合二，把“乙”(举例 UID 114514) 推送到另外两个群
[[bilibili.routes]]
uids = ["36081646"]                  # 支持多个 UID (36081646是洛天依)
groups = ["114514", "1919810"]  # 对应要推送到的QQ群号


# 旧写法（可选，用作兜底；若保留，会与上面的 routes 聚合去重）
# uids = ["36081646"]
# groups = ["114514", "1919810"]

# 建议配置 Cookie（SESSDATA 等），提高接口稳定性。没有也能跑，但更容易 412/风控。
cookie = ""

[image]
send_images = true          # 需要时可关图
downscale_width = 720       # 压缩宽度
jpeg_quality = 85           # JPG 质量
base64_chunk_limit = 5500000  # 最大 Base64 字节数（约5.5MB）
per_image_delay_ms = 1600   # 每张图发送间隔

[fallback]
# 打不开新/老接口时，尝试 HTML 兜底解析
enable_html = true
